# Monte Carlo simulation parameters

# Number of simulation runs
runs: 100

# Number of days to simulate per run
days_to_simulate: 30

# Sensitivity analysis parameter ranges
sensitivity_analysis:
  # Routing accuracy values to test
  routing_accuracy_range:
    - 0.60
    - 0.70
    - 0.80
    - 0.85
    - 0.90
    - 0.95
  
  # Query volume values to test
  query_volume_range:
    - 500
    - 1000
    - 1500
    - 2000
    - 2500
  
  # Complex query percentage values to test
  complex_query_percentage:
    - 0.05
    - 0.10
    - 0.15
    - 0.20
    - 0.25
